
(* File generated by ${QMCCHEM_PATH}/src/create_properties.py. Do not
   modify here
 *)

type t =
| Cpu
| Wall
| Accep
| D_var_jast_a_up_dn
| D_var_jast_a_up_up
| D_var_jast_b_up_dn
| D_var_jast_b_up_up
| D_var_jast_core_a1
| D_var_jast_core_b1
| D_var_jast_een_e_a
| D_var_jast_een_e_b
| D_var_jast_een_n
| D_var_jast_pen
| Density1d
| Dipole
| Drift_mod
| E_kin
| E_loc
| E_loc_one
| E_loc_per_electron
| E_loc_split_core
| E_loc_two
| E_nucl
| E_pot
| E_pot_one
| N_s_inverted
| N_s_updated
| N_s_updates
| Voronoi_charges
| Voronoi_charges_covariance
| Voronoi_dipoles
| Wf_extension
| D_var_jast_a_up_dn_qmcvar
| D_var_jast_a_up_up_qmcvar
| D_var_jast_b_up_dn_qmcvar
| D_var_jast_b_up_up_qmcvar
| D_var_jast_core_a1_qmcvar
| D_var_jast_core_b1_qmcvar
| D_var_jast_een_e_a_qmcvar
| D_var_jast_een_e_b_qmcvar
| D_var_jast_een_n_qmcvar
| D_var_jast_pen_qmcvar
| Density1d_qmcvar
| Dipole_qmcvar
| Drift_mod_qmcvar
| E_kin_qmcvar
| E_loc_qmcvar
| E_loc_one_qmcvar
| E_loc_per_electron_qmcvar
| E_loc_split_core_qmcvar
| E_loc_two_qmcvar
| E_nucl_qmcvar
| E_pot_qmcvar
| E_pot_one_qmcvar
| N_s_inverted_qmcvar
| N_s_updated_qmcvar
| N_s_updates_qmcvar
| Voronoi_charges_qmcvar
| Voronoi_charges_covariance_qmcvar
| Voronoi_dipoles_qmcvar
| Wf_extension_qmcvar
;;

let calc = function
| Cpu 
| Wall
| Accep -> true
| D_var_jast_a_up_dn
| D_var_jast_a_up_dn_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_a_up_dn ()) then
        Ezfio.get_properties_d_var_jast_a_up_dn ()
      else
        false
    end

| D_var_jast_a_up_up
| D_var_jast_a_up_up_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_a_up_up ()) then
        Ezfio.get_properties_d_var_jast_a_up_up ()
      else
        false
    end

| D_var_jast_b_up_dn
| D_var_jast_b_up_dn_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_b_up_dn ()) then
        Ezfio.get_properties_d_var_jast_b_up_dn ()
      else
        false
    end

| D_var_jast_b_up_up
| D_var_jast_b_up_up_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_b_up_up ()) then
        Ezfio.get_properties_d_var_jast_b_up_up ()
      else
        false
    end

| D_var_jast_core_a1
| D_var_jast_core_a1_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_core_a1 ()) then
        Ezfio.get_properties_d_var_jast_core_a1 ()
      else
        false
    end

| D_var_jast_core_b1
| D_var_jast_core_b1_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_core_b1 ()) then
        Ezfio.get_properties_d_var_jast_core_b1 ()
      else
        false
    end

| D_var_jast_een_e_a
| D_var_jast_een_e_a_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_een_e_a ()) then
        Ezfio.get_properties_d_var_jast_een_e_a ()
      else
        false
    end

| D_var_jast_een_e_b
| D_var_jast_een_e_b_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_een_e_b ()) then
        Ezfio.get_properties_d_var_jast_een_e_b ()
      else
        false
    end

| D_var_jast_een_n
| D_var_jast_een_n_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_een_n ()) then
        Ezfio.get_properties_d_var_jast_een_n ()
      else
        false
    end

| D_var_jast_pen
| D_var_jast_pen_qmcvar -> 
    begin
      if (Ezfio.has_properties_d_var_jast_pen ()) then
        Ezfio.get_properties_d_var_jast_pen ()
      else
        false
    end

| Density1d
| Density1d_qmcvar -> 
    begin
      if (Ezfio.has_properties_density1d ()) then
        Ezfio.get_properties_density1d ()
      else
        false
    end

| Dipole
| Dipole_qmcvar -> 
    begin
      if (Ezfio.has_properties_dipole ()) then
        Ezfio.get_properties_dipole ()
      else
        false
    end

| Drift_mod
| Drift_mod_qmcvar -> 
    begin
      if (Ezfio.has_properties_drift_mod ()) then
        Ezfio.get_properties_drift_mod ()
      else
        false
    end

| E_kin
| E_kin_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_kin ()) then
        Ezfio.get_properties_e_kin ()
      else
        false
    end

| E_loc
| E_loc_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc ()) then
        Ezfio.get_properties_e_loc ()
      else
        true
    end

| E_loc_one
| E_loc_one_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc_one ()) then
        Ezfio.get_properties_e_loc_one ()
      else
        false
    end

| E_loc_per_electron
| E_loc_per_electron_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc_per_electron ()) then
        Ezfio.get_properties_e_loc_per_electron ()
      else
        false
    end

| E_loc_split_core
| E_loc_split_core_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc_split_core ()) then
        Ezfio.get_properties_e_loc_split_core ()
      else
        false
    end

| E_loc_two
| E_loc_two_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc_two ()) then
        Ezfio.get_properties_e_loc_two ()
      else
        false
    end

| E_nucl
| E_nucl_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_nucl ()) then
        Ezfio.get_properties_e_nucl ()
      else
        false
    end

| E_pot
| E_pot_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_pot ()) then
        Ezfio.get_properties_e_pot ()
      else
        false
    end

| E_pot_one
| E_pot_one_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_pot_one ()) then
        Ezfio.get_properties_e_pot_one ()
      else
        false
    end

| N_s_inverted
| N_s_inverted_qmcvar -> 
    begin
      if (Ezfio.has_properties_n_s_inverted ()) then
        Ezfio.get_properties_n_s_inverted ()
      else
        false
    end

| N_s_updated
| N_s_updated_qmcvar -> 
    begin
      if (Ezfio.has_properties_n_s_updated ()) then
        Ezfio.get_properties_n_s_updated ()
      else
        false
    end

| N_s_updates
| N_s_updates_qmcvar -> 
    begin
      if (Ezfio.has_properties_n_s_updates ()) then
        Ezfio.get_properties_n_s_updates ()
      else
        false
    end

| Voronoi_charges
| Voronoi_charges_qmcvar -> 
    begin
      if (Ezfio.has_properties_voronoi_charges ()) then
        Ezfio.get_properties_voronoi_charges ()
      else
        false
    end

| Voronoi_charges_covariance
| Voronoi_charges_covariance_qmcvar -> 
    begin
      if (Ezfio.has_properties_voronoi_charges_covariance ()) then
        Ezfio.get_properties_voronoi_charges_covariance ()
      else
        false
    end

| Voronoi_dipoles
| Voronoi_dipoles_qmcvar -> 
    begin
      if (Ezfio.has_properties_voronoi_dipoles ()) then
        Ezfio.get_properties_voronoi_dipoles ()
      else
        false
    end

| Wf_extension
| Wf_extension_qmcvar -> 
    begin
      if (Ezfio.has_properties_wf_extension ()) then
        Ezfio.get_properties_wf_extension ()
      else
        false
    end

;;

let u _ = ();;

let set_calc = function
| Cpu 
| Wall
| Accep -> u
| D_var_jast_a_up_dn 
| D_var_jast_a_up_dn_qmcvar -> 
      Ezfio.set_properties_d_var_jast_a_up_dn 

| D_var_jast_a_up_up 
| D_var_jast_a_up_up_qmcvar -> 
      Ezfio.set_properties_d_var_jast_a_up_up 

| D_var_jast_b_up_dn 
| D_var_jast_b_up_dn_qmcvar -> 
      Ezfio.set_properties_d_var_jast_b_up_dn 

| D_var_jast_b_up_up 
| D_var_jast_b_up_up_qmcvar -> 
      Ezfio.set_properties_d_var_jast_b_up_up 

| D_var_jast_core_a1 
| D_var_jast_core_a1_qmcvar -> 
      Ezfio.set_properties_d_var_jast_core_a1 

| D_var_jast_core_b1 
| D_var_jast_core_b1_qmcvar -> 
      Ezfio.set_properties_d_var_jast_core_b1 

| D_var_jast_een_e_a 
| D_var_jast_een_e_a_qmcvar -> 
      Ezfio.set_properties_d_var_jast_een_e_a 

| D_var_jast_een_e_b 
| D_var_jast_een_e_b_qmcvar -> 
      Ezfio.set_properties_d_var_jast_een_e_b 

| D_var_jast_een_n 
| D_var_jast_een_n_qmcvar -> 
      Ezfio.set_properties_d_var_jast_een_n 

| D_var_jast_pen 
| D_var_jast_pen_qmcvar -> 
      Ezfio.set_properties_d_var_jast_pen 

| Density1d 
| Density1d_qmcvar -> 
      Ezfio.set_properties_density1d 

| Dipole 
| Dipole_qmcvar -> 
      Ezfio.set_properties_dipole 

| Drift_mod 
| Drift_mod_qmcvar -> 
      Ezfio.set_properties_drift_mod 

| E_kin 
| E_kin_qmcvar -> 
      Ezfio.set_properties_e_kin 

| E_loc 
| E_loc_qmcvar -> 
      Ezfio.set_properties_e_loc 

| E_loc_one 
| E_loc_one_qmcvar -> 
      Ezfio.set_properties_e_loc_one 

| E_loc_per_electron 
| E_loc_per_electron_qmcvar -> 
      Ezfio.set_properties_e_loc_per_electron 

| E_loc_split_core 
| E_loc_split_core_qmcvar -> 
      Ezfio.set_properties_e_loc_split_core 

| E_loc_two 
| E_loc_two_qmcvar -> 
      Ezfio.set_properties_e_loc_two 

| E_nucl 
| E_nucl_qmcvar -> 
      Ezfio.set_properties_e_nucl 

| E_pot 
| E_pot_qmcvar -> 
      Ezfio.set_properties_e_pot 

| E_pot_one 
| E_pot_one_qmcvar -> 
      Ezfio.set_properties_e_pot_one 

| N_s_inverted 
| N_s_inverted_qmcvar -> 
      Ezfio.set_properties_n_s_inverted 

| N_s_updated 
| N_s_updated_qmcvar -> 
      Ezfio.set_properties_n_s_updated 

| N_s_updates 
| N_s_updates_qmcvar -> 
      Ezfio.set_properties_n_s_updates 

| Voronoi_charges 
| Voronoi_charges_qmcvar -> 
      Ezfio.set_properties_voronoi_charges 

| Voronoi_charges_covariance 
| Voronoi_charges_covariance_qmcvar -> 
      Ezfio.set_properties_voronoi_charges_covariance 

| Voronoi_dipoles 
| Voronoi_dipoles_qmcvar -> 
      Ezfio.set_properties_voronoi_dipoles 

| Wf_extension 
| Wf_extension_qmcvar -> 
      Ezfio.set_properties_wf_extension 

;;

let of_string s = 
  match (String.lowercase s) with 
  | "cpu" -> Cpu
  | "wall" -> Wall
  | "accep" -> Accep
  | "d_var_jast_a_up_dn" -> D_var_jast_a_up_dn
  | "d_var_jast_a_up_up" -> D_var_jast_a_up_up
  | "d_var_jast_b_up_dn" -> D_var_jast_b_up_dn
  | "d_var_jast_b_up_up" -> D_var_jast_b_up_up
  | "d_var_jast_core_a1" -> D_var_jast_core_a1
  | "d_var_jast_core_b1" -> D_var_jast_core_b1
  | "d_var_jast_een_e_a" -> D_var_jast_een_e_a
  | "d_var_jast_een_e_b" -> D_var_jast_een_e_b
  | "d_var_jast_een_n" -> D_var_jast_een_n
  | "d_var_jast_pen" -> D_var_jast_pen
  | "density1d" -> Density1d
  | "dipole" -> Dipole
  | "drift_mod" -> Drift_mod
  | "e_kin" -> E_kin
  | "e_loc" -> E_loc
  | "e_loc_one" -> E_loc_one
  | "e_loc_per_electron" -> E_loc_per_electron
  | "e_loc_split_core" -> E_loc_split_core
  | "e_loc_two" -> E_loc_two
  | "e_nucl" -> E_nucl
  | "e_pot" -> E_pot
  | "e_pot_one" -> E_pot_one
  | "n_s_inverted" -> N_s_inverted
  | "n_s_updated" -> N_s_updated
  | "n_s_updates" -> N_s_updates
  | "voronoi_charges" -> Voronoi_charges
  | "voronoi_charges_covariance" -> Voronoi_charges_covariance
  | "voronoi_dipoles" -> Voronoi_dipoles
  | "wf_extension" -> Wf_extension
  | "d_var_jast_a_up_dn_qmcvar" -> D_var_jast_a_up_dn_qmcvar
  | "d_var_jast_a_up_up_qmcvar" -> D_var_jast_a_up_up_qmcvar
  | "d_var_jast_b_up_dn_qmcvar" -> D_var_jast_b_up_dn_qmcvar
  | "d_var_jast_b_up_up_qmcvar" -> D_var_jast_b_up_up_qmcvar
  | "d_var_jast_core_a1_qmcvar" -> D_var_jast_core_a1_qmcvar
  | "d_var_jast_core_b1_qmcvar" -> D_var_jast_core_b1_qmcvar
  | "d_var_jast_een_e_a_qmcvar" -> D_var_jast_een_e_a_qmcvar
  | "d_var_jast_een_e_b_qmcvar" -> D_var_jast_een_e_b_qmcvar
  | "d_var_jast_een_n_qmcvar" -> D_var_jast_een_n_qmcvar
  | "d_var_jast_pen_qmcvar" -> D_var_jast_pen_qmcvar
  | "density1d_qmcvar" -> Density1d_qmcvar
  | "dipole_qmcvar" -> Dipole_qmcvar
  | "drift_mod_qmcvar" -> Drift_mod_qmcvar
  | "e_kin_qmcvar" -> E_kin_qmcvar
  | "e_loc_qmcvar" -> E_loc_qmcvar
  | "e_loc_one_qmcvar" -> E_loc_one_qmcvar
  | "e_loc_per_electron_qmcvar" -> E_loc_per_electron_qmcvar
  | "e_loc_split_core_qmcvar" -> E_loc_split_core_qmcvar
  | "e_loc_two_qmcvar" -> E_loc_two_qmcvar
  | "e_nucl_qmcvar" -> E_nucl_qmcvar
  | "e_pot_qmcvar" -> E_pot_qmcvar
  | "e_pot_one_qmcvar" -> E_pot_one_qmcvar
  | "n_s_inverted_qmcvar" -> N_s_inverted_qmcvar
  | "n_s_updated_qmcvar" -> N_s_updated_qmcvar
  | "n_s_updates_qmcvar" -> N_s_updates_qmcvar
  | "voronoi_charges_qmcvar" -> Voronoi_charges_qmcvar
  | "voronoi_charges_covariance_qmcvar" -> Voronoi_charges_covariance_qmcvar
  | "voronoi_dipoles_qmcvar" -> Voronoi_dipoles_qmcvar
  | "wf_extension_qmcvar" -> Wf_extension_qmcvar
  | p -> failwith ("unknown property "^p) ;;


let to_string = function
| Cpu -> "Cpu"
| Wall -> "Wall"
| Accep -> "Accep" 
| D_var_jast_a_up_dn -> "D_var_jast_a_up_dn" 
| D_var_jast_a_up_up -> "D_var_jast_a_up_up" 
| D_var_jast_b_up_dn -> "D_var_jast_b_up_dn" 
| D_var_jast_b_up_up -> "D_var_jast_b_up_up" 
| D_var_jast_core_a1 -> "D_var_jast_core_a1" 
| D_var_jast_core_b1 -> "D_var_jast_core_b1" 
| D_var_jast_een_e_a -> "D_var_jast_een_e_a" 
| D_var_jast_een_e_b -> "D_var_jast_een_e_b" 
| D_var_jast_een_n -> "D_var_jast_een_n" 
| D_var_jast_pen -> "D_var_jast_pen" 
| Density1d -> "Density1d" 
| Dipole -> "Dipole" 
| Drift_mod -> "Drift_mod" 
| E_kin -> "E_kin" 
| E_loc -> "E_loc" 
| E_loc_one -> "E_loc_one" 
| E_loc_per_electron -> "E_loc_per_electron" 
| E_loc_split_core -> "E_loc_split_core" 
| E_loc_two -> "E_loc_two" 
| E_nucl -> "E_nucl" 
| E_pot -> "E_pot" 
| E_pot_one -> "E_pot_one" 
| N_s_inverted -> "N_s_inverted" 
| N_s_updated -> "N_s_updated" 
| N_s_updates -> "N_s_updates" 
| Voronoi_charges -> "Voronoi_charges" 
| Voronoi_charges_covariance -> "Voronoi_charges_covariance" 
| Voronoi_dipoles -> "Voronoi_dipoles" 
| Wf_extension -> "Wf_extension" 
| D_var_jast_a_up_dn_qmcvar -> "D_var_jast_a_up_dn_qmcvar" 
| D_var_jast_a_up_up_qmcvar -> "D_var_jast_a_up_up_qmcvar" 
| D_var_jast_b_up_dn_qmcvar -> "D_var_jast_b_up_dn_qmcvar" 
| D_var_jast_b_up_up_qmcvar -> "D_var_jast_b_up_up_qmcvar" 
| D_var_jast_core_a1_qmcvar -> "D_var_jast_core_a1_qmcvar" 
| D_var_jast_core_b1_qmcvar -> "D_var_jast_core_b1_qmcvar" 
| D_var_jast_een_e_a_qmcvar -> "D_var_jast_een_e_a_qmcvar" 
| D_var_jast_een_e_b_qmcvar -> "D_var_jast_een_e_b_qmcvar" 
| D_var_jast_een_n_qmcvar -> "D_var_jast_een_n_qmcvar" 
| D_var_jast_pen_qmcvar -> "D_var_jast_pen_qmcvar" 
| Density1d_qmcvar -> "Density1d_qmcvar" 
| Dipole_qmcvar -> "Dipole_qmcvar" 
| Drift_mod_qmcvar -> "Drift_mod_qmcvar" 
| E_kin_qmcvar -> "E_kin_qmcvar" 
| E_loc_qmcvar -> "E_loc_qmcvar" 
| E_loc_one_qmcvar -> "E_loc_one_qmcvar" 
| E_loc_per_electron_qmcvar -> "E_loc_per_electron_qmcvar" 
| E_loc_split_core_qmcvar -> "E_loc_split_core_qmcvar" 
| E_loc_two_qmcvar -> "E_loc_two_qmcvar" 
| E_nucl_qmcvar -> "E_nucl_qmcvar" 
| E_pot_qmcvar -> "E_pot_qmcvar" 
| E_pot_one_qmcvar -> "E_pot_one_qmcvar" 
| N_s_inverted_qmcvar -> "N_s_inverted_qmcvar" 
| N_s_updated_qmcvar -> "N_s_updated_qmcvar" 
| N_s_updates_qmcvar -> "N_s_updates_qmcvar" 
| Voronoi_charges_qmcvar -> "Voronoi_charges_qmcvar" 
| Voronoi_charges_covariance_qmcvar -> "Voronoi_charges_covariance_qmcvar" 
| Voronoi_dipoles_qmcvar -> "Voronoi_dipoles_qmcvar" 
| Wf_extension_qmcvar -> "Wf_extension_qmcvar" 
;;


let is_scalar = function
| Cpu -> true
| Wall -> true
| Accep -> true 
| D_var_jast_a_up_dn | D_var_jast_a_up_dn_qmcvar -> false 
| D_var_jast_a_up_up | D_var_jast_a_up_up_qmcvar -> false 
| D_var_jast_b_up_dn | D_var_jast_b_up_dn_qmcvar -> false 
| D_var_jast_b_up_up | D_var_jast_b_up_up_qmcvar -> false 
| D_var_jast_core_a1 | D_var_jast_core_a1_qmcvar -> false 
| D_var_jast_core_b1 | D_var_jast_core_b1_qmcvar -> false 
| D_var_jast_een_e_a | D_var_jast_een_e_a_qmcvar -> false 
| D_var_jast_een_e_b | D_var_jast_een_e_b_qmcvar -> false 
| D_var_jast_een_n | D_var_jast_een_n_qmcvar -> false 
| D_var_jast_pen | D_var_jast_pen_qmcvar -> false 
| Density1d | Density1d_qmcvar -> false 
| Dipole | Dipole_qmcvar -> false 
| Drift_mod | Drift_mod_qmcvar -> false 
| E_kin | E_kin_qmcvar -> true 
| E_loc | E_loc_qmcvar -> true 
| E_loc_one | E_loc_one_qmcvar -> true 
| E_loc_per_electron | E_loc_per_electron_qmcvar -> false 
| E_loc_split_core | E_loc_split_core_qmcvar -> false 
| E_loc_two | E_loc_two_qmcvar -> true 
| E_nucl | E_nucl_qmcvar -> true 
| E_pot | E_pot_qmcvar -> true 
| E_pot_one | E_pot_one_qmcvar -> true 
| N_s_inverted | N_s_inverted_qmcvar -> true 
| N_s_updated | N_s_updated_qmcvar -> true 
| N_s_updates | N_s_updates_qmcvar -> true 
| Voronoi_charges | Voronoi_charges_qmcvar -> false 
| Voronoi_charges_covariance | Voronoi_charges_covariance_qmcvar -> false 
| Voronoi_dipoles | Voronoi_dipoles_qmcvar -> false 
| Wf_extension | Wf_extension_qmcvar -> true 
;;


let all = [ Cpu ; Wall ; Accep ; 
 D_var_jast_a_up_dn ;  D_var_jast_a_up_up ;  D_var_jast_b_up_dn ;  D_var_jast_b_up_up ;  D_var_jast_core_a1 ;  D_var_jast_core_b1 ;  D_var_jast_een_e_a ;  D_var_jast_een_e_b ;  D_var_jast_een_n ;  D_var_jast_pen ;  Density1d ;  Dipole ;  Drift_mod ;  E_kin ;  E_loc ;  E_loc_one ;  E_loc_per_electron ;  E_loc_split_core ;  E_loc_two ;  E_nucl ;  E_pot ;  E_pot_one ;  N_s_inverted ;  N_s_updated ;  N_s_updates ;  Voronoi_charges ;  Voronoi_charges_covariance ;  Voronoi_dipoles ;  Wf_extension ; ];;
